### ISSUE TITLE
Add AppVeyor instructions with artefact deployment in 2.0

### ISSUE THREAD

**Issue by akien-mga** [GodotBuilder/godot-builds#3]
It would basically require cherry-picking the appveyor.yml file from @Marqin's #1, and add the necessary instructions to deploy to GitHub releases using the same encrypted token as in .travis.yml.

Relevant doc: https://www.appveyor.com/docs/deployment/github

**Comment by akien-mga** [comment]
Gave it a try with 47db2d7, let's see how it goes.

**Comment by Marqin** [comment]
You can track status [here](https://ci.appveyor.com/project/GodotBuilder/godot-builds/build/1.0.14).

**Comment by akien-mga** [comment]
So, it seemed to fail with:

```
Packaging artifacts...OK
Uploading artifact godot\bin\godot.windows.opt.tools.64.exe (19.7 MB)...OK
Deploying using GitHub provider
Creating "master_20161205" release for repository "GodotBuilder/godot-builds" tag "master_20161205" commit "47db2d70dc1edf0436a1218b3a34974ae3c4710b"...Error creating GitHub release: Error reading repository 'GodotBuilder/godot-builds' releases: 401 - Unauthorized
```

So maybe I was wrong to assume that I could reuse the token for Travis CI in AppVeyor. I'll have a new one generated.

**Comment by akien-mga** [comment]
I fixed this a while ago actually, by generating a new token for AppVeyor.
