### ISSUE TITLE
Add appveyor builds for winrt templates

### ISSUE THREAD

**Issue by akien-mga** [GodotBuilder/godot-builds#4]
CC @vnen. What would be needed to do this?

**Comment by vnen** [comment]
If they have the Windows SDK (it seems they do), nothing else is needed. Just build normally with `scons p=winrt`.

**Comment by akien-mga** [comment]
How about ANGLE?

**Comment by vnen** [comment]
Completely forgot about that... 🤔

I guess we can add a built version of ANGLE to this repo and set the env var pointing to it. Likely better than adding all the sources and compiling together.

**Comment by akien-mga** [comment]
We could host a 7zipped built version of ANGLE on our FTP and download it in the chroot during build. We don't do release builds that often so it wouldn't be a big issue bandwidth-wise.

**Comment by akien-mga** [comment]
@vnen I gave you access to the repo, could you upload to this GH release a zipped or 7zipped (smaller) archive of your built ANGLE version that could be used out of the box in the build environment? https://github.com/GodotBuilder/godot-builds/releases/tag/_tools (click Edit release, you can then upload an archive normally).

**Comment by vnen** [comment]
@akien-mga will do. I'm doing some tests to check the minimal amount of files it needs.

**Comment by vnen** [comment]
Uploaded.

I noticed the ANGLE lib file is quite big (~230MB for each of the 3 architectures). However, it does compress very well, ended up with a 60MB 7zip file with all targets. Do you prefer to split it in 3 different archives, one for each architecture?

**Comment by akien-mga** [comment]
Let's start with a single archive and see how it goes :)

**Comment by akien-mga** [comment]
So basically I download it, uncompress at the root of the git folder, and set `ANGLE_SRC_ROOT` accordingly? Do you know if a relative path would work, or should I find a way to get the `cwd` in the Windows shell?

**Comment by akien-mga** [comment]
Also, how does it work to build the ARM flavour? See the current setup: https://github.com/GodotBuilder/godot-builds/blob/master/appveyor.yml
Can the amd64 shell build the ARM binaries out of the box?

**Comment by vnen** [comment]
Based on my test you can't use relative path in `ANGLE_SRC_PATH`, but SCons finds the absolute path if the env var starts with `#`. So either absolute or the relative with a prepended `#` will work.

As for ARM build, if you set `ARCH` to either `amd64_arm` or `x86_arm` it should work. Those are the proper `vcvarsall.bat` arguments to set up the ARM toolchain.
